import type {Metadata} from "next";
import "./globals.css";
import {Fjalla_One, Orbitron, Inter} from "next/font/google"

const fjallaOne = Fjalla_One({subsets: ["latin"], weight: "400"});
export const metadata: Metadata = {
    title: "CashTrackr - Aplicación MVC",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={fjallaOne.className}>
            {children}
        </body>
        </html>
    );
}
